DEBUG:rea.configuration:Validating configuration for rule extraction.
DEBUG:rea.configuration:Validating configuration for evaluation.
DEBUG:rea.data.data:Created new Data instance.
DEBUG:rea.extraction.extraction:Starting rule extraction dnnre
2022-03-03 13:16:48.835823: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:48.925824: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:48.926055: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:48.927148: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-03 13:16:48.928642: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:48.929044: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:48.929345: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:50.228028: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:50.228431: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:50.228803: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-03 13:16:50.228980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3389 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tom/Uni/G3_Rule-Extraction_SB/40_Realisation/99_Final_System/rea/__main__.py", line 40, in <module>
    main()
  File "/home/tom/Uni/G3_Rule-Extraction_SB/40_Realisation/99_Final_System/rea/__main__.py", line 36, in main
    REA(conf_paths).run(*flags)
  File "/home/tom/Uni/G3_Rule-Extraction_SB/40_Realisation/99_Final_System/rea/rea.py", line 91, in run
    extraction.run(data)
  File "/home/tom/Uni/G3_Rule-Extraction_SB/40_Realisation/99_Final_System/rea/extraction/extraction.py", line 64, in run
    self.rules = self._run_dnnre()
  File "/home/tom/Uni/G3_Rule-Extraction_SB/40_Realisation/99_Final_System/rea/extraction/extraction.py", line 102, in _run_dnnre
    trained_model = TrainedModel(self.trained_model_path, output_classes,
  File "/home/tom/Uni/G3_Rule-Extraction_SB/40_Realisation/99_Final_System/rea/extraction/dnnre/model/trained_model.py", line 37, in __init__
    self.__compute_layerwise_activations()
  File "/home/tom/Uni/G3_Rule-Extraction_SB/40_Realisation/99_Final_System/rea/extraction/dnnre/model/trained_model.py", line 72, in __compute_layerwise_activations
    data=partial_model.predict(data_x), columns=neuron_labels)
  File "/home/tom/.local/share/virtualenvs/99_Final_System-VQtj6te5/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/tom/.local/share/virtualenvs/99_Final_System-VQtj6te5/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/home/tom/.local/share/virtualenvs/99_Final_System-VQtj6te5/lib/python3.9/site-packages/keras/engine/training.py", line 1801, in predict_function  *
        return step_function(self, iterator)
    File "/home/tom/.local/share/virtualenvs/99_Final_System-VQtj6te5/lib/python3.9/site-packages/keras/engine/training.py", line 1790, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/tom/.local/share/virtualenvs/99_Final_System-VQtj6te5/lib/python3.9/site-packages/keras/engine/training.py", line 1783, in run_step  **
        outputs = model.predict_step(data)
    File "/home/tom/.local/share/virtualenvs/99_Final_System-VQtj6te5/lib/python3.9/site-packages/keras/engine/training.py", line 1751, in predict_step
        return self(x, training=False)
    File "/home/tom/.local/share/virtualenvs/99_Final_System-VQtj6te5/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home/tom/.local/share/virtualenvs/99_Final_System-VQtj6te5/lib/python3.9/site-packages/keras/engine/input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 28, 28, 1), found shape=(None, 784)
